name: aligner
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.0.0
    - cached-property==1.5.2
    - cachetools==5.0.0
    - certifi==2019.11.28
    - charset-normalizer==2.0.12
    - click==8.1.3
    - coloredlogs==15.0.1
    - cupy-cuda112==8.5.0
    - cycler==0.10.0
    - einops==0.4.1
    - fastrlock==0.4
    - filelock==3.6.0
    - flatbuffers==22.11.23
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - greenlet==2.0.1
    - grpcio==1.46.0
    - h5py==3.6.0
    - hdf5storage==0.1.18
    - huggingface-hub==0.5.1
    - humanfriendly==10.0
    - idna==3.3
    - imageio==2.8.0
    - imgviz==1.5.1
    - importlib-metadata==4.11.3
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kiwisolver==1.1.0
    - kornia==0.2.0
    - llvmlite==0.38.0
    - lmdb==1.3.0
    - markdown==3.3.7
    - matplotlib==3.2.1
    - mpmath==1.2.1
    - networkx==2.6.3
    - numba==0.55.1
    - numpy==1.21.6
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.6.0.163
    - oauthlib==3.2.0
    - onnx==1.12.0
    - onnxruntime-gpu==1.10.0
    - opencv-python==4.2.0.32
    - packaging==21.3
    - pandas==1.0.3
    - pillow==9.1.0
    - piqa==1.2.2
    - playwright==1.31.1
    - prettytable==3.3.0
    - protobuf==3.20.1
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pyee==9.0.4
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytorch-fid==0.2.1
    - pytz==2019.3
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.0
    - regex==2022.4.24
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.53
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.14.0
    - sympy==1.10.1
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==1.7
    - tensorrt==8.5.1.7
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.6.11
    - tokenizers==0.12.1
    - torch==1.11.0+cu113
    - torch2trt==0.4.0
    - torchaudio==0.11.0+cu113
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - torchtoolbox==0.1.8.2
    - torchvision==0.12.0+cu113
    - tornado==6.2
    - tqdm==4.64.0
    - transformers==4.18.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - visdom==0.1.8.9
    - wcwidth==0.2.5
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - xlrd==1.2.0
    - xlwt==1.3.0
    - zipp==3.8.0
